### ISSUE TITLE
"Hook Download to external Downloader" and Package names for the External Downloader 

### ISSUE THREAD

**Issue by kaisen7887** [driftywinds/YT-builds#1]
Finding the package names for the External Downloaders are annoying especially with the current Android updates not gonna lie.
Can we have the external download section similar to the revanced extended?
 Like this:
![Screenshot_20240307-143148](https://github.com/driftywinds/YT-builds/assets/53758833/78c80024-0968-4796-b794-4e3b8c1cf3d8)

**Comment by driftywinds** [comment]
I don't code the patches I simply build apks. Cannot help you with this, please go to the actual respective repository of the patches.
